### ISSUE TITLE
Support for AWSAppSync?

### ISSUE THREAD

**Issue by ptrkstr** [swift-aws/aws-sdk-appleos#2]
**Is your feature request related to a problem? Please describe.**
Currently AWSAppSync only supports Cocoapods/Carthage.

**Describe the solution you'd like**
Add the ability to add AWSAppSync using Swift Package Manager.

**Describe alternatives you've considered**
N/A

**Additional context**
Repo for AWSAppSync can be found here:
https://github.com/awslabs/aws-mobile-appsync-sdk-ios

**Comment by adam-fowler** [comment]
Did you mean to add this issue here? 

We have the AppSync api here https://github.com/swift-aws/aws-sdk-appleos/tree/master/Sources/AWSSDKSwift/Services/AppSync and you can use the Swift Package Manager to include it in your project. But we cannot setup SWP for other github repositories.

**Comment by ptrkstr** [comment]
You're right, this isn't the right repo for this.
Thanks for replying @adam-fowler .
