### ISSUE TITLE
Clarity on support for iOS 13.x and Xcode 11.x

### ISSUE THREAD

**Issue by robert-will-brown** [swift-aws/aws-sdk-appleos#4]
Hi,

**Is your feature request related to a problem? Please describe.**
I'm having trouble using aws-sdk-appleos with iOS 13 and Xcode 11.1.

**Describe the solution you'd like**

- Initially, confirmation that aws-sdk-appleos **won't** work with the above configuration so I know that it's not me 😃
- A rough roadmap if it will be fixed on those tools
- Eventually a concise instruction and preferably an example project compatible with the above tools

**Comment by adam-fowler** [comment]
Hi Robert, 
what are your exact problems?
In the near future aws-sdk-appleos is going to be collapsed back down into aws-sdk-swift but I imagine the issues you are having now might continue with aws-sdk-swift so details would be useful.
thank you

**Comment by robert-will-brown** [comment]
Thanks for the response Adam.

It should be said that I’m a complete newbie to swift development and Xcode, so I apologise in advance if I’m doing something silly.  

I’ve tried adding aws-sdk-appleos using the Swift Package Manager (which I think according to [this](https://github.com/swift-aws/aws-sdk-swift/issues/167) doesn’t work at the moment), and also using the `swift package generate-xcodeproj`  approach.

This is as far as I've managed to get using the example code - `Use of undeclared type 'Future'`.

![PastedGraphic-1](https://user-images.githubusercontent.com/7024743/67878832-deb7c480-fb33-11e9-8e5f-ca9d0749c0ac.png)

Many thanks,

**Comment by adam-fowler** [comment]
Ah you'll have to excuse us. It looks like the example code isn't correct. It has not been updated. I have updated it now.

- You need to add an `import AWSSDKSwiftCore` at the top of the file as the type alias Future is in that module. It is an alias to the swift-nio object `EventLoopFuture` which you could use instead.
- The `then` function has been renamed to `flatMap`.

If I were you I would look up the docs on swift nio eventloops and futures https://apple.github.io/swift-nio/docs/current/NIO/Classes/EventLoopFuture.html before going much further. The whole aws-sdk-swift project is based off swift-nio and you need to know how `EventLoopFuture` works. If that is too much initially you can make life easy for yourself by just called `wait()` on the result of any aws-sdk-swift function you call. That will return the output object.

**Comment by robert-will-brown** [comment]
Thats really helpful Adam, thanks - I'll read up on event loops as suggested.
